name: blackbird_electron
description: TODO
environment:
  sdk: ">=2.0.0-dev <=3.0.0"
dependencies:
  js: ^0.6.0
  node_interop: ^1.0.0
  angular: ^5.1.0
  angular_components: ^0.10.1
  angular_router: ^2.0.0-alpha+19
  bootstrap_sass: 
  blackbird:
    path: ../dart/core
  dart_node_serialport:
    path: ../node/serial
dev_dependencies:
  build_runner: ^1.0.0
  build_web_compilers: ^0.4.0
  pedantic: ^1.0.0
  angular_test: ^2.1.0
  build_test: ^0.10.3
  test: ^1.5.1
  sass_builder: ^2.1.2
  blackbird_generators:
    path: ../dart/generators
  source_gen:
  source_gen_helpers: 
    path: ../../dart/source_gen_helpers
  build_node_compilers:
