name: blackbird_electron
description: TODO
environment:
  sdk: ">=2.0.0-dev <=3.0.0"
dependencies:
  js: ^0.6.0
  node_interop: ^1.0.0
  angular: ^5.1.0
  angular_components: ^0.10.1
dev_dependencies:
  build_runner: ^1.0.0
  build_web_compilers: ^0.4.0
  pedantic: ^1.0.0
  angular_test: ^2.1.0
  build_test: ^0.10.3
  test: ^1.5.1