targets:
  $default:
    builders:
      blackbird_core|blackbird_core:
        enabled: true

builders:
  blackbird_core:
    target: ":blackbird_core"
    import: "package:blackbird_core/device_generator.dart"
    builder_factories: ["builder"]
    build_extensions: {".dart": [".blackbird_core_device.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]