name: blackbird
version: 0.0.1
description: >
authors:
- Matthias Sokolowski <matthias.sokolowski@googlemail.com>

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  rmi: ^0.0.3
  built_value: ^6.1.6
  built_collection: ^4.1.0
  blackbird_device_generator:
    path: ../device_generator
  
dev_dependencies:
  tuple:
  rmi_generator: ^0.0.3
  built_value_generator: ^6.1.6
  build_runner: ^1.1.2
  build_test:
  test:
  source_gen_helpers: 
    path: ../../dart/source_gen_helpers

dependency_overrides:
  rmi: 
    path: ../../dart/remote_method_invocation/rmi
  rmi_generator: 
    path: ../../dart/remote_method_invocation/rmi_generator