name: blackbird_core
version: 0.0.1
description: >
authors:
- Matthias Sokolowski <matthias.sokolowski@googlemail.com>

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  rmi: ^0.0.3
  built_value: ^6.1.6
  built_collection: ^4.1.0
  
dev_dependencies:
  rmi_generator: ^0.0.3
  built_value_generator: ^6.1.6
  build_runner: ^1.1.2
