name: blackbird
version: 0.0.1
description: >
authors:
- Matthias Sokolowski <matthias.sokolowski@googlemail.com>

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  blackbird_common:
    path: ../common
  rmi: ^0.0.3
  tuple:
  built_value: ^6.1.6
  built_collection: ^4.1.0
  json_annotation:

dev_dependencies:
  json_serializable:
    path: ../../../dart/json_serializable/json_serializable
  built_value_generator: ^6.1.6
  build_runner: ^1.1.2
  build_test:
  test:
  rmi_generator: ^0.0.3
  blackbird_generators:
    path: ../generators
  source_gen_helpers: 
    path: ../../../dart/source_gen_helpers

dependency_overrides:
  rmi: 
    path: ../../../dart/remote_method_invocation/rmi
  rmi_generator: 
    path: ../../../dart/remote_method_invocation/rmi_generator