name: blackbird
version: 0.0.1
description: >
authors:
- Matthias Sokolowski <matthias.sokolowski@googlemail.com>

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  logging:
  async:
  rmi: 
    path: ../../../dart/remote_method_invocation/rmi
    # git:
    #   url: https://github.com/MatzeS/dart_rmi
    #   ref: develop
    #   path: rmi
  tuple:
  json_annotation:
  json_serialization:
    git:
      url: https://github.com/MatzeS/json_serializable
      ref: feature/blackbird
      path: json_serialization

dev_dependencies:
  blackbird_common:
    path: ../common
  json_serializable:
    git:
      url: https://github.com/MatzeS/json_serializable
      ref: feature/blackbird
      path: json_serializable  
  build_runner: ^1.1.2
  build_test:
  test:
  rmi_generator: 
    path: ../../../dart/remote_method_invocation/rmi_generator
    # git:
    #   url: https://github.com/MatzeS/dart_rmi
    #   ref: develop
    #   path: rmi_generator
  blackbird_generators:
    path: ../generators
