targets:
  $default:
    builders:
      blackbird_generators|device_generator:
        enabled: true
      blackbird_generators|filtered_dependency_builder_type_generator:
        enabled: true

builders:
  device_generator:
    target: ":blackbird_dblackbird_generatorsevice_generator"
    import: "package:blackbird_generators/src/generator.dart"
    builder_factories: ["builder"]
    build_extensions: {".dart": [".device_generator.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
  filtered_dependency_builder_type_generator:
    target: ":blackbird_generators"
    import: "package:blackbird_generators/src/filtered_dependency_builder/generator.dart"
    builder_factories: ["builder"]
    build_extensions: {".dart": [".filtered_dependency_builder.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]