name: blackbird_generators
version: 0.0.1
description: >
authors:
- Matthias Sokolowski <matthias.sokolowski@googlemail.com>

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  tuple:
  blackbird_common:
    path: ../common
  source_gen_helpers: 0.0.2
  json_serializable:
    git:
      url: https://github.com/MatzeS/json_serializable
      ref: feature/blackbird
      path: json_serializable  

dev_dependencies:
  test:
  source_gen: 
  build_runner: ^1.1.2
  build_test: