name: blackbird_generators
version: 0.0.1
description: >
authors:
- Matthias Sokolowski <matthias.sokolowski@googlemail.com>

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  tuple:

dev_dependencies:
  test:
  source_gen: 
  source_gen_helpers: 
    path: ../../../dart/source_gen_helpers
  build_runner: ^1.1.2
  build_test:

  
dependency_overrides:
  rmi: 
    path: ../../../dart/remote_method_invocation/rmi
  rmi_generator: 
    path: ../../../dart/remote_method_invocation/rmi_generator