name: blackbird_common
version: 0.0.1
description: >
authors:
- Matthias Sokolowski <matthias.sokolowski@googlemail.com>

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  source_gen_helpers: 0.0.2

dev_dependencies:
  build_runner: ^1.1.2
  build_test:
  test:
